# Generated by Django 3.2.11 on 2022-01-06 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='fecha_pub',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
