# Generated by Django 3.2.11 on 2022-01-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_alter_pregunta_fecha_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='fecha_pub',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
